# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-06-21 00:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock_name', models.CharField(max_length=200)),
                ('stock_price', models.CharField(max_length=200)),
                ('stock_gain', models.CharField(max_length=200)),
                ('market_gain', models.CharField(max_length=200)),
            ],
        ),
    ]
